# ── UI Strings ──────────────────────────────────────────────
# These strings appear in the app's interface (menus, dialogs).
# Provide translations for each language you want to support.
# The app uses the user's configured language setting.
#
# Structure:
#   STRINGS = {
#       "pt": { "key": "valor", ... },
#       "en": { "key": "value", ... },
#       "jp": { "key": "値", ... },
#   }
#
# Required keys (the app expects these):
#   greeting, ollama_started, ollama_not_found,
#   history_cleared, no_mic_found, mic_configured,
#   gemini_configured, gemini_no_key, groq_configured,
#   groq_no_key, hf_configured, hf_no_token,
#   profile_saved_name, profile_saved, restarting_model,
#   alarm_stopped_generic, alarm_stopped_msg, alarm_deleted,
#   alarm_added, speech_timer_title, accessibility_interval_title,
#   accessibility_min_title, accessibility_max_title,
#   audio_interval_title, audio_min_title, audio_max_title,
#   speech_min_title, speech_max_title, speech_timer_desc,
#   accessibility_desc, audio_desc, btn_cancel, btn_save,
#   btn_close, menu_inteligence, menu_permissions,
#   menu_profile, menu_model, menu_alarms, menu_fish_setup,
#   menu_tts, menu_mic_stt, stt_shortcut_title,
#   stt_shortcut_markup, stt_shortcut_placeholder,
#   fish_setup_title, fish_key_placeholder, fish_voice_placeholder,
#   fish_configured, fish_no_key, tts_provider_fish,
#   tts_provider_edge, tts_provider_pyttsx3, tts_provider_auto

STRINGS = {
    "pt": {
        "greeting": "Ola! Como voce esta? ^_^",
        "ollama_started": "Ollama ligado! Pronto pra conversar! ^_^",
        "ollama_not_found": "Nao achei o Ollama... Vou usar frases prontas mesmo!",
        "history_cleared": "Historico limpo! ^_^",
        "no_mic_found": "Nenhum microfone encontrado!",
        "mic_configured": "Microfone configurado! ^_^",
        "gemini_configured": "Gemini configurado! ^_^",
        "gemini_no_key": "Nao colou nenhuma chave... Tenta de novo!",
        "groq_configured": "Groq configurado! ^_^",
        "groq_no_key": "Nao colou nenhuma chave... Tenta de novo!",
        "hf_configured": "HuggingFace configurado! ^_^",
        "hf_no_token": "Nao colou nenhum token... Tenta de novo!",
        "profile_saved_name": "Anotado! Vou te chamar de {name} agora! ^_^",
        "profile_saved": "Perfil atualizado! ^_^",
        "restarting_model": "Reiniciando pra carregar {model}...",
        "alarm_stopped_generic": "Hora do alarme!",
        "alarm_stopped_msg": "Alarme desligado! ^_^",
        "alarm_deleted": "Alarme removido!",
        "alarm_added": "Alarme adicionado!",
        "speech_timer_title": "Timer de fala",
        "accessibility_interval_title": "Intervalo da leitura automatica",
        "accessibility_min_title": "Minimo entre leituras",
        "accessibility_max_title": "Maximo entre leituras",
        "audio_interval_title": "Intervalo da transcricao de audio",
        "audio_min_title": "Minimo entre audios",
        "audio_max_title": "Maximo entre audios",
        "speech_min_title": "Intervalo minimo entre falas",
        "speech_max_title": "Intervalo maximo entre falas",
        "speech_timer_desc": "De quanto em quanto tempo o pet fala algo aleatorio?",
        "accessibility_desc": "De quanto em quanto tempo o pet descreve a tela?",
        "audio_desc": "De quanto em quanto tempo o pet transcreve audio?",
        "btn_cancel": "Cancelar",
        "btn_save": "Salvar",
        "btn_close": "Fechar",
        "menu_inteligence": "Inteligencia",
        "menu_permissions": "Permissoes",
        "menu_profile": "Perfil",
        "menu_model": "Modelo do pet",
        "menu_alarms": "Alarmes",
        "menu_fish_setup": "Configurar Fish Audio",
        "menu_tts": "TTS",
        "menu_mic_stt": "Microfone (STT)",
        "stt_shortcut_title": "Atalho do microfone",
        "stt_shortcut_markup": "Tecla atual: {current}\n\nPressione a tecla que deseja usar\npara Pressionar pra Falar.",
        "stt_shortcut_placeholder": "Pressione uma tecla...",
        "fish_setup_title": "Fish Audio",
        "fish_key_placeholder": "Chave da API Fish Audio",
        "fish_voice_placeholder": "ID da voz (opcional)",
        "fish_configured": "Fish Audio configurado! ^_^",
        "fish_no_key": "Nao colou nenhuma chave... Tenta de novo!",
        "tts_provider_fish": "Fish Audio",
        "tts_provider_edge": "Edge TTS",
        "tts_provider_pyttsx3": "pyttsx3",
        "tts_provider_auto": "Automatico",
        "menu_libras": "Traducao para Libras (escrita)",
        "menu_always_on_top": "Sempre no topo",
        "menu_wallpaper": "Modo papel de parede",
        "menu_fullscreen": "Tela cheia",
    },
    "en": {
        "greeting": "Hello! How are you? ^_^",
        "ollama_started": "Ollama started! Ready to chat! ^_^",
        "ollama_not_found": "Couldn't find Ollama... I'll use scripted phrases!",
        "history_cleared": "History cleared! ^_^",
        "no_mic_found": "No microphone found!",
        "mic_configured": "Microphone configured! ^_^",
        "gemini_configured": "Gemini configured! ^_^",
        "gemini_no_key": "No key provided... Try again!",
        "groq_configured": "Groq configured! ^_^",
        "groq_no_key": "No key provided... Try again!",
        "hf_configured": "HuggingFace configured! ^_^",
        "hf_no_token": "No token provided... Try again!",
        "profile_saved_name": "Got it! I'll call you {name} now! ^_^",
        "profile_saved": "Profile updated! ^_^",
        "restarting_model": "Restarting to load {model}...",
        "alarm_stopped_generic": "Alarm time!",
        "alarm_stopped_msg": "Alarm dismissed! ^_^",
        "alarm_deleted": "Alarm removed!",
        "alarm_added": "Alarm added!",
        "speech_timer_title": "Speech timer",
        "accessibility_interval_title": "Screen reading interval",
        "accessibility_min_title": "Minimum between readings",
        "accessibility_max_title": "Maximum between readings",
        "audio_interval_title": "Audio transcription interval",
        "audio_min_title": "Minimum between audios",
        "audio_max_title": "Maximum between audios",
        "speech_min_title": "Minimum interval between speeches",
        "speech_max_title": "Maximum interval between speeches",
        "speech_timer_desc": "How often should the pet say something random?",
        "accessibility_desc": "How often should the pet describe the screen?",
        "audio_desc": "How often should the pet transcribe audio?",
        "btn_cancel": "Cancel",
        "btn_save": "Save",
        "btn_close": "Close",
        "menu_inteligence": "Intelligence",
        "menu_permissions": "Permissions",
        "menu_profile": "Profile",
        "menu_model": "Pet model",
        "menu_alarms": "Alarms",
        "menu_fish_setup": "Configure Fish Audio",
        "menu_tts": "TTS",
        "menu_mic_stt": "Microphone (STT)",
        "stt_shortcut_title": "Microphone shortcut",
        "stt_shortcut_markup": "Current key: {current}\n\nPress the key you want to use\nfor Push to Talk.",
        "stt_shortcut_placeholder": "Press a key...",
        "fish_setup_title": "Fish Audio",
        "fish_key_placeholder": "Fish Audio API Key",
        "fish_voice_placeholder": "Voice ID (optional)",
        "fish_configured": "Fish Audio configured! ^_^",
        "fish_no_key": "No key provided... Try again!",
        "tts_provider_fish": "Fish Audio",
        "tts_provider_edge": "Edge TTS",
        "tts_provider_pyttsx3": "pyttsx3",
        "tts_provider_auto": "Auto",
        "menu_libras": "Translate to Libras (written)",
        "menu_always_on_top": "Always on top",
        "menu_wallpaper": "Wallpaper mode",
        "menu_fullscreen": "Fullscreen",
    },
}
