STRINGS = {
    "pt": {
        "greeting": "Oii! Que bom te ver! ^_^",
        "ollama_started": "Ollama ligado! Tô pronta pra conversar! ^_^",
        "ollama_not_found": "Hmm, não achei o Ollama... Vou usar frases prontas mesmo!",
        "history_cleared": "Histórico limpo! ^_^",
        "no_mic_found": "Nenhum microfone encontrado!",
        "mic_configured": "Microfone configurado! ^_^",
        "gemini_configured": "Gemini configurado! Vou usar IA do Google! ^_^",
        "gemini_no_key": "Não colou nenhuma chave... Tenta de novo!",
        "groq_configured": "Groq configurado! Vou usar a IA mais rápida! ^_^",
        "groq_no_key": "Não colou nenhuma chave... Tenta de novo!",
        "hf_configured": "HuggingFace configurado! Agora vou usar a IA da comunidade! ^_^",
        "hf_no_token": "Não colou nenhum token... Tenta de novo!",
        "profile_saved_name": "Anotado! Vou te chamar de {name} agora! ^_^",
        "profile_saved": "Perfil atualizado! ^_^",
        "restarting_model": "Reiniciando pra carregar {model}...",
        "alarm_stopped_generic": "Hora do alarme! 🎵",
        "alarm_stopped_msg": "Alarme desligado! ^_^",
        "alarm_deleted": "Alarme removido!",
        "alarm_added": "Alarme adicionado! 💃",
        "speech_timer_title": "Timer de fala",
        "accessibility_interval_title": "Intervalo da leitura automática",
        "accessibility_min_title": "Mínimo entre leituras",
        "accessibility_max_title": "Máximo entre leituras",
        "audio_interval_title": "Intervalo da transcrição de áudio",
        "audio_min_title": "Mínimo entre áudios",
        "audio_max_title": "Máximo entre áudios",
        "speech_min_title": "Intervalo mínimo entre falas",
        "speech_max_title": "Intervalo máximo entre falas",
        "speech_exact_title": "Intervalo exato entre falas",
        "window_scale_title": "Tamanho da Janela",
        "mic_device_title": "Dispositivo do Microfone",
        "global_shortcut_title": "Atalho Global (Win+V)",
        "stt_shortcut_title": "Atalho do Microfone",
        "gemini_setup_title": "Configurar Gemini",
        "groq_setup_title": "Configurar Groq",
        "hf_setup_title": "Configurar HuggingFace",
        "profile_title": "Meu Perfil",
        "add_alarm_title": "Adicionar Alarme",
        "speech_timer_label": "Daqui a quantos segundos o pet deve falar?",
        "accessibility_interval_label": "A cada quantos segundos a tela deve ser lida?",
        "accessibility_min_label": "Segundos mínimo entre leituras?",
        "accessibility_max_label": "Segundos máximo entre leituras?",
        "audio_interval_label": "A cada quantos segundos o áudio deve ser transcrito?",
        "audio_min_label": "Segundos mínimo entre transcrições?",
        "audio_max_label": "Segundos máximo entre transcrições?",
        "speech_min_label": "Segundos mínimo entre falas aleatórias?",
        "speech_max_label": "Segundos máximo entre falas aleatórias?",
        "speech_exact_label": "A cada quantos segundos o pet deve falar?",
        "window_scale_label": "Ajuste o tamanho da janela do pet:",
        "window_scale_default_mark": "Padrão",
        "mic_device_label": "Escolha o dispositivo de entrada:",
        "mic_choose_device": "Dispositivo do Microfone",
        "btn_cancel": "Cancelar",
        "btn_ok": "Ok",
        "btn_save": "Salvar",
        "btn_add": "Adicionar",
        "global_shortcut_markup": "<b>Atalho Global: Win + V</b>\n\nO atalho <b>Win+V</b> permite usar o pressionar pra falar de qualquer lugar da tela, mesmo com o app sem foco.\n\nPara funcionar, adicione esta linha ao seu\narquivo de atalhos do compositor:\n\n<tt><span size=\"smaller\">Mod+V  {{ spawn-sh \"bash {path} toggle\"; }}</span></tt>\n\nOu execute manualmente:\n<tt><span size=\"smaller\">bash {path} press   # inicia gravação\nbash {path} release # para gravação\nbash {path} toggle  # alterna liga/desliga</span></tt>",
        "stt_shortcut_markup": "<b>Atalho para Pressionar pra Falar</b>\n\nEssa tecla funciona quando o app está em foco.\nUse <b>Win+V</b> (atalho global) para funcionar\nde qualquer lugar da tela.\n\nPressione a tecla desejada no campo abaixo.\nSegure para gravar, solte para transcrever.\n\nAtual: <b>{current}</b>",
        "gemini_markup": "<b>Gemini API Key</b>\n\nO Gemini tem um plano gratuito generoso (60 req/min).\n\n1. Acesse: https://aistudio.google.com/apikey\n2. Clique em \"Criar chave de API\"\n3. Copie a chave e cole abaixo\n\nNão precisa de cartão de crédito.",
        "groq_markup": "<b>Groq API Key</b>\n\nGroq é 100% gratuito e MUITO rápido!\nUsa GPU própria (LPU) pra rodar Llama 3, Gemma e Mixtral.\n\n1. Acesse: https://console.groq.com/keys\n2. Clique em \"Create API Key\"\n3. Copie a chave e cole abaixo\n\nNão precisa de cartão de crédito. ~600 req/dia grátis!",
        "hf_markup": "<b>HuggingFace API Token</b>\n\nHuggingFace oferece inferência grátis com token!\nUse modelos como DialoGPT para conversar.\n\n1. Acesse: https://huggingface.co/settings/tokens\n2. Clique em \"New token\"\n3. Escolha permissão \"read\" e copie o token\n4. Cole abaixo\n\nGratuito, sem cartão de crédito!",
        "profile_markup": "<b>Como a IA deve te tratar</b>\n\nEsses dados são salvos localmente e usados\napenas para a IA te conhecer melhor.",
        "add_alarm_markup": "<b>Novo Alarme</b>\n\nEscolha o horário. Pode criar quantos quiser!",
        "add_alarm_name_placeholder": "Ex: Acordar, Almoço, Remédio...",
        "add_alarm_hour_label": "Hora:",
        "add_alarm_min_label": "Min:",
        "add_alarm_name_label": "Nome (opcional):",
        "menu_chat": "Conversar",
        "menu_alarm": "Alarme",
        "menu_add_alarm": "Adicionar alarme...",
        "menu_stop_alarm": "Parar Alarme",
        "menu_model": "Modelo do pet",
        "menu_settings": "Configurações",
        "menu_appearance": "🖥 Aparência",
        "menu_always_on_top": "Sempre no topo",
        "menu_wallpaper": "Modo papel de parede",
        "menu_fullscreen": "Tela cheia",
        "menu_bubble_side": "Lado do balão",
        "menu_bubble_auto": "Automático",
        "menu_bubble_left": "Esquerda",
        "menu_bubble_right": "Direita",
        "menu_speech_behavior": "Comportamento de fala",
        "menu_speech_interrupt": "Interromper anterior",
        "menu_speech_wait": "Esperar acabar",
        "menu_window_size": "Tamanho da janela...",
        "menu_automation": "🤖 Automação",
        "menu_model_defaults": "Padrão do Modelo",
        "menu_screen_reading": "Leitura de tela",
        "menu_enable": "Ativar",
        "menu_random": "Aleatório",
        "menu_exact": "Exato",
        "menu_minimum": "Mínimo...",
        "menu_maximum": "Máximo...",
        "menu_interval": "Intervalo...",
        "menu_desktop_audio": "Áudio do desktop",
        "menu_random_speech": "Falas aleatórias",
        "menu_timer": "Timer...",
        "menu_audio_cfg": "🎤 Áudio",
        "menu_mic_stt": "Microfone (STT)",
        "menu_hold_to_talk": "Pressionar pra falar",
        "menu_mic_open": "Microfone aberto",
        "menu_mic_shortcut": "Atalho do microfone...",
        "menu_global_shortcut": "Atalho global (Win+V)...",
        "menu_mic_device": "Dispositivo do microfone...",
        "menu_intelligence": "🧠 Inteligência",
        "menu_ai_enable": "IA Ativada",
        "menu_ai_provider": "Provedor de IA",
        "menu_provider_auto": "Automático",
        "menu_provider_groq": "Groq (grátis)",
        "menu_provider_gemini": "Gemini (Google)",
        "menu_provider_hf": "API (Hugging Face)",
        "menu_provider_ollama": "Ollama (local)",
        "menu_provider_phrases": "Frases prontas",
        "menu_configure_gemini": "Configurar Gemini...",
        "menu_configure_groq": "Configurar Groq...",
        "menu_configure_hf": "Configurar HuggingFace...",
        "menu_ollama_model": "Modelo Ollama",
        "menu_permissions": "Permissões",
        "menu_perm_read_file": "Ler arquivos",
        "menu_perm_list_files": "Listar pastas",
        "menu_perm_run_command": "Executar comandos",
        "menu_perm_write_file": "Escrever arquivos",
        "menu_perm_screenshot": "Capturar tela",
        "menu_perm_open_url": "Abrir URLs",
        "menu_perm_listen": "Escutar sons do desktop",
        "menu_profile": "👤 Meu Perfil...",
        "menu_about": "ℹ Sobre",
        "menu_clear_history": "Limpar Histórico",
        "menu_quit": "Sair",
        "menu_language": "🌐 Idioma",
        "about_comments": "Um pet virtual da Kasane Teto",
        "profile_name_label": "Seu nome:",
        "profile_name_placeholder": "Ex: João, Maria...",
        "profile_bio_label": "Detalhes extras (opcional):",
        "profile_bio_placeholder": "Ex: pronomes, idade, apelido...",
        "gemini_entry_placeholder": "Cole sua chave Gemini aqui...",
        "groq_entry_placeholder": "Cole sua chave Groq aqui...",
        "hf_entry_placeholder": "Cole seu token HuggingFace aqui...",
        "gemini_link_label": "Abrir Google AI Studio",
        "groq_link_label": "Abrir Groq Console",
        "hf_link_label": "Abrir HuggingFace Tokens",
        "stt_shortcut_placeholder": "Pressione uma tecla",
        "alarm_toggle_label": "Ativado",
        "alarm_delete_label": "Deletar",
        "alarm_stopped": "Alarme desligado! ^_^",
        "alarm_deleted_msg": "Alarme removido!",
        "alarm_added_msg": "Alarme adicionado! 💃",
        "menu_tts": "Voz do Assistente",
        "menu_mic_mode": "Modo do microfone",
        "menu_tts_provider": "Provedor de Voz",
        "tts_provider_auto": "Automático",
        "tts_provider_fish": "Fish Audio",
        "tts_provider_edge": "Edge-TTS",
        "tts_provider_pyttsx": "pyttsx3",
        "menu_tts_device": "Dispositivo de saída...",
        "menu_tts_volume": "Volume da voz",
        "tts_volume_title": "Volume da Voz",
        "tts_volume_label": "Nível de volume (0-100):",
        "tts_device_title": "Dispositivo de Áudio",
        "tts_device_label": "Escolha o dispositivo de saída:",
        "no_tts_device": "Nenhum dispositivo encontrado!",
        "menu_shortcuts": "Atalhos",
        "menu_configure_fish": "Configurar Fish Audio...",
        "fish_setup_title": "Configurar Fish Audio",
        "fish_key_placeholder": "Cole sua chave Fish Audio aqui...",
        "fish_voice_placeholder": "ID da voz (opcional)",
        "fish_configured": "Fish Audio configurado! ^_^",
        "fish_no_key": "Não colou nenhuma chave...",
        "lang_pt": "Português",
        "lang_en": "English",
        "lang_jp": "日本語",
        "menu_voice": "🎤 Voz",
        "menu_microphone": "🎧 Microfone",
        "settings_window": "Janela",
        "settings_appearance_desc": "Aqui você mexe no visual do seu novo vício.",
        "settings_bubble": "Balão de fala",
        "settings_model": "Modelo",
        "settings_language": "Idioma",
        "settings_voice_section": "Voz do Assistente",
        "settings_voice_provider_section": "Provedor de Voz",
        "settings_fish_section": "Fish Audio",
        "settings_mic_section": "Microfone (STT)",
        "settings_mic_mode_section": "Modo de operação",
        "settings_shortcuts_section": "Atalhos",
        "settings_ai_section": "Inteligência Artificial",
        "settings_ai_provider_section": "Provedor de IA",
        "settings_api_keys_section": "Chaves de API",
        "settings_ollama_section": "Ollama (local)",
        "settings_profile_section": "Perfil",
        "settings_permissions_section": "Permissões",
        "settings_screen_reading_section": "Leitura de tela",
        "settings_audio_section": "Áudio do desktop",
        "settings_speech_section": "Falas aleatórias",
        "settings_speak_section": "Falar agora",
        "settings_alarms_section": "Alarmes",
        "settings_about_section": "Sobre",
        "settings_credits_section": "Agradecimentos",
        "settings_voice_title": "Título da Voz",
        "settings_model_defaults_section": "Padrões do Modelo",
        "settings_bubble_desc": "Onde e como o pet joga a fala.",
        "settings_model_desc": "Trocar de roupa do pet. Ele tem mais variedade que seu guarda-roupa.",
        "settings_language_desc": "Mudar o idioma. O pet é poliglota, diferente de você.",
        "settings_language_restart": "Português, English ou 日本語. Requer reinício.",
        "settings_model_item_desc": "Cada modelo vem com sprites, frases e um estilo único.",
        "settings_voice_desc": "Pra quando você quer ouvir groselhas em voz alta.",
        "settings_voice_provider_choose": "Quem vai emprestar a voz pro seu pet.",
        "settings_output_device_desc": "Qual placa de som vai gemer as frases do pet.",
        "settings_fish_desc": "Pra quem quer voz de dublador mas tem orçamento de coxinha.",
        "settings_mic_desc": "Pra você falar com o pet. Não, ele não vai te julgar. Mentira, vai sim.",
        "settings_mic_mode_desc": "Como ativar o microfone. Escolha sabiamente (ou não).",
        "settings_shortcuts_desc": "Teclas mágicas pra ativar o microfone.",
        "settings_ai_desc": "O cérebro do pet. Desative se quiser um bichinho burrinho mas feliz.",
        "settings_ai_provider_desc": "Escolha sua fonte de alucinações favorita.",
        "settings_api_keys_desc": "A chave mágica que libera os poderes do pet (e talvez seu cartão de crédito).",
        "settings_ollama_desc": "IA rodando no seu PC. Provedor pros paranóicos (leia-se: sensatos).",
        "settings_profile_desc": "Ensine seu pet a te chamar pelo nome. Ou por 'chefe'. Ou por 'pé-rapado'.",
        "settings_permissions_desc": "Deixar a IA ler seus arquivos é tipo dar a senha do Wi-Fi pro vizinho.",
        "settings_screen_reading_desc": "O pet fica bisbilhotando sua tela e comentando. Fofoqueiro mode ON.",
        "settings_audio_desc": "O pet escuta os sons do PC. Tipo sua mãe quando você tá no quarto.",
        "settings_speech_desc": "O pet fala do nada. Igual seus pensamentos intrusivos às 3 da manhã.",
        "settings_speak_desc": "Faz o pet falar depois de X segundos. Tipo alarme, mas mais fofinho.",
        "settings_alarms_desc": "Crie alarmes pro pet te lembrar de coisas. Tipo sua consciência, mas mais bonitinha.",
        "settings_about_subtitle": "Um pet virtual de mesa com IA integrada.",
        "settings_created_by": "Criado por",
        "settings_original_char": "Personagem original",
        "settings_technologies": "Tecnologias",
        "settings_credits_text": "Obrigada por usar o Mate Helper! Este projeto é open source e feito com carinho (e café). Contribuições são bem-vindas! ❤️",
        "settings_no_alarms": "Nenhum alarme configurado. Você é desorganizado ou só não liga mesmo?",
        "settings_configure_fish": "Configurar Fish Audio...",
        "settings_edit_profile": "Editar perfil...",
        "settings_open_timer": "Abrir timer...",
        "settings_add_alarm_btn": "Adicionar alarme...",
        "settings_configure_shortcut": "Configurar atalho...",
        "settings_global_help": "Ajuda: Win+V...",
        "settings_new_alarm": "Novo alarme",
        "settings_always_on_top_desc": "Mantém o pet sempre visível. Igual sua ansiedade.",
        "settings_wallpaper_desc": "Pet ocupa a tela inteira. Perfeito pra streamar ou fingir que você tem amigo.",
        "settings_pet_size_desc": "De 3 a 10. No 10 ele fica do tamanho dos seus boletos.",
        "settings_bubble_side_desc": "De que lado o balão aparece. Tipo política, mas sem treta.",
        "settings_speech_behavior_desc": "Interromper igual sua mãe ou esperar igual seu Wi-Fi.",
        "settings_voice_enable_desc": "O pet fala as mensagens em voz alta. Tipo locutor de rádio, mas mais fofinho.",
        "settings_voice_provider_desc": "Fish Audio tem vozes de cinema (mas custa um rim). Edge-TTS é de grátis.",
        "settings_voice_volume_desc": "0 = mudo (finalmente, paz). 100 = seu vizinho bate na porta.",
        "settings_fish_configure_desc": "Abra o diálogo pra configurar sua chave e escolher a voz.",
        "settings_mic_enable_desc": "Quando ativado, você pode falar groselhas pro pet.",
        "settings_mic_mode_choose_desc": "Pressionar pra falar = walkie-talkie. Aberto = sua mãe escutando tudo.",
        "settings_mic_device_desc": "Qual microfone vai capturar sua voz (e seus segredos).",
        "settings_mic_shortcut_desc": "Tecla usada pro Pressionar pra Falar (quando o app tá em foco).",
        "settings_global_shortcut_desc": "Win+V funciona de qualquer lugar. Tipo stalker, mas com propósito.",
        "settings_ai_enabled_desc": "Quando desligado, só frases prontas. É tipo ter um pet de verdade: fofo, mas limitado.",
        "settings_ai_provider_choose_desc": "Automático tenta Groq (grátis), Gemini, HuggingFace e por fim frases prontas. Ordem: sorte.",
        "settings_gemini_btn_desc": "Plano grátis generoso (60 req/min). Google te ama (e seus dados).",
        "settings_groq_btn_desc": "100% grátis e muito rápido. ~600 req/dia. O rei do custo benefício.",
        "settings_hf_btn_desc": "Inferência grátis com token de leitura. Open-source vibes.",
        "settings_ollama_model_desc": "Modelo de IA instalado localmente. Nada vai pra nuvem. Nem seus segredos.",
        "settings_profile_btn_desc": "Nome e detalhes pro pet te conhecer melhor (ou te zuar).",
        "settings_model_defaults_desc": "Quando ativado, usa os intervalos que vieram com o modelo. É tipo comer o que deram.",
        "settings_screen_enable_desc": "Captura a tela e o pet comenta o que vê. Sabe quando você sente que tão te olhando?",
        "settings_screen_mode_desc": "Aleatório: intervalo varia. Exato: igual pontualidade brasileira (nunca).",
        "settings_spin_min_desc": "Tempo mínimo entre fofocadas.",
        "settings_spin_max_desc": "Tempo máximo entre fofocadas.",
        "settings_spin_exact_desc": "Tempo fixo. Igual novela: sempre no mesmo horário.",
        "settings_audio_enable_desc": "Grava o áudio do sistema e o pet comenta. Fofoca em estéreo.",
        "settings_audio_mode_desc": "Aleatório: ele ouve quando quer. Exato: ele OUVE.",
        "settings_spin_audio_min_desc": "Mínimo entre fofocadas auditivas.",
        "settings_spin_audio_max_desc": "Máximo entre fofocadas auditivas.",
        "settings_spin_audio_exact_desc": "Tempo fixo entre fofocadas. Igual boletim meteorológico.",
        "settings_speech_enable_desc": "O pet solta frases espontâneas. Porque silêncio é constrangedor.",
        "settings_speech_mode_desc": "Aleatório: ele fala quando quer. Exato: igual reunião marcada.",
        "settings_spin_speech_min_desc": "Mínimo entre pensamentos intrusivos.",
        "settings_spin_speech_max_desc": "Máximo entre pensamentos intrusivos.",
        "settings_spin_speech_exact_desc": "Intervalo fixo. Igual fiscal vir todo mês.",
        "settings_speech_timer_desc": "Define um cronômetro pro pet falar. Útil pra lembrar você de levantar (ou não).",
        "settings_new_alarm_desc": "Cria um alarme novo. Não, ele não vai te acordar de verdade. Talvez.",
        "settings_gemini_label": "Gemini (Google)",
        "settings_groq_label": "Groq",
        "settings_hf_label": "HuggingFace",
        "settings_pet_size_scale": "De 3 a 10. No 10 ele fica do tamanho dos seus boletos.",
        "settings_spin_min_label": "Intervalo mínimo (s)",
        "settings_spin_max_label": "Intervalo máximo (s)",
        "settings_spin_exact_label": "Intervalo exato (s)",
        "system_default": "Padrão do sistema",
        "enable_microphone": "Ativar microfone",
        "settings_mic_mode": "Modo",
        "settings_mic_device": "Dispositivo",
        "settings_my_profile": "Meu Perfil",
        "settings_speech_timer": "Timer de fala",
        "settings_api_key": "Chave de API",
    },
    "en": {
        "greeting": "Hii! So good to see you! ^_^",
        "ollama_started": "Ollama started! Ready to chat! ^_^",
        "ollama_not_found": "Hmm, couldn't find Ollama... I'll use preset phrases instead!",
        "history_cleared": "History cleared! ^_^",
        "no_mic_found": "No microphone found!",
        "mic_configured": "Microphone configured! ^_^",
        "gemini_configured": "Gemini configured! I'll use Google's AI! ^_^",
        "gemini_no_key": "No key provided... Try again!",
        "groq_configured": "Groq configured! I'll use the fastest AI! ^_^",
        "groq_no_key": "No key provided... Try again!",
        "hf_configured": "HuggingFace configured! Now I'll use the community's AI! ^_^",
        "hf_no_token": "No token provided... Try again!",
        "profile_saved_name": "Got it! I'll call you {name} now! ^_^",
        "profile_saved": "Profile updated! ^_^",
        "restarting_model": "Restarting to load {model}...",
        "alarm_stopped_generic": "Alarm time! 🎵",
        "alarm_stopped_msg": "Alarm turned off! ^_^",
        "alarm_deleted": "Alarm removed!",
        "alarm_added": "Alarm added! 💃",
        "speech_timer_title": "Speech Timer",
        "accessibility_interval_title": "Auto-reading interval",
        "accessibility_min_title": "Minimum between readings",
        "accessibility_max_title": "Maximum between readings",
        "audio_interval_title": "Audio transcription interval",
        "audio_min_title": "Minimum between audios",
        "audio_max_title": "Maximum between audios",
        "speech_min_title": "Minimum interval between speeches",
        "speech_max_title": "Maximum interval between speeches",
        "speech_exact_title": "Exact interval between speeches",
        "window_scale_title": "Window Size",
        "mic_device_title": "Microphone Device",
        "global_shortcut_title": "Global Shortcut (Win+V)",
        "stt_shortcut_title": "Microphone Shortcut",
        "gemini_setup_title": "Configure Gemini",
        "groq_setup_title": "Configure Groq",
        "hf_setup_title": "Configure HuggingFace",
        "profile_title": "My Profile",
        "add_alarm_title": "Add Alarm",
        "speech_timer_label": "After how many seconds should the pet speak?",
        "accessibility_interval_label": "Every how many seconds should the screen be read?",
        "accessibility_min_label": "Minimum seconds between readings?",
        "accessibility_max_label": "Maximum seconds between readings?",
        "audio_interval_label": "Every how many seconds should audio be transcribed?",
        "audio_min_label": "Minimum seconds between transcriptions?",
        "audio_max_label": "Maximum seconds between transcriptions?",
        "speech_min_label": "Minimum seconds between random speech?",
        "speech_max_label": "Maximum seconds between random speech?",
        "speech_exact_label": "Every how many seconds should the pet speak?",
        "window_scale_label": "Adjust the pet's window size:",
        "window_scale_default_mark": "Default",
        "mic_device_label": "Choose the input device:",
        "mic_choose_device": "Microphone Device",
        "btn_cancel": "Cancel",
        "btn_ok": "Ok",
        "btn_save": "Save",
        "btn_add": "Add",
        "global_shortcut_markup": "<b>Global Shortcut: Win + V</b>\n\nThe <b>Win+V</b> shortcut lets you press-to-talk from anywhere on the screen, even when the app is not focused.\n\nTo use it, add this line to your\ncompositor shortcuts file:\n\n<tt><span size=\"smaller\">Mod+V  {{ spawn-sh \"bash {path} toggle\"; }}</span></tt>\n\nOr run manually:\n<tt><span size=\"smaller\">bash {path} press   # start recording\nbash {path} release # stop recording\nbash {path} toggle  # toggle on/off</span></tt>",
        "stt_shortcut_markup": "<b>Press-to-Talk Shortcut</b>\n\nThis key works when the app is in focus.\nUse <b>Win+V</b> (global shortcut) for it to work\nfrom anywhere on the screen.\n\nPress the desired key in the field below.\nHold to record, release to transcribe.\n\nCurrent: <b>{current}</b>",
        "gemini_markup": "<b>Gemini API Key</b>\n\nGemini has a generous free plan (60 req/min).\n\n1. Visit: https://aistudio.google.com/apikey\n2. Click \"Create API Key\"\n3. Copy the key and paste it below\n\nNo credit card required.",
        "groq_markup": "<b>Groq API Key</b>\n\nGroq is 100% free and VERY fast!\nIt uses its own GPU (LPU) to run Llama 3, Gemma, and Mixtral.\n\n1. Visit: https://console.groq.com/keys\n2. Click \"Create API Key\"\n3. Copy the key and paste it below\n\nNo credit card needed. ~600 req/day free!",
        "hf_markup": "<b>HuggingFace API Token</b>\n\nHuggingFace offers free inference with a token!\nUse models like DialoGPT to chat.\n\n1. Visit: https://huggingface.co/settings/tokens\n2. Click \"New token\"\n3. Choose \"read\" permission and copy the token\n4. Paste it below\n\nFree, no credit card!",
        "profile_markup": "<b>How the AI should address you</b>\n\nThis data is saved locally and used\nonly for the AI to get to know you better.",
        "add_alarm_markup": "<b>New Alarm</b>\n\nPick a time. You can create as many as you want!",
        "add_alarm_name_placeholder": "Ex: Wake up, Lunch, Medicine...",
        "add_alarm_hour_label": "Hour:",
        "add_alarm_min_label": "Min:",
        "add_alarm_name_label": "Name (optional):",
        "menu_chat": "Chat",
        "menu_alarm": "Alarm",
        "menu_add_alarm": "Add alarm...",
        "menu_stop_alarm": "Stop Alarm",
        "menu_model": "Pet model",
        "menu_settings": "Settings",
        "menu_appearance": "🖥 Appearance",
        "menu_always_on_top": "Always on top",
        "menu_wallpaper": "Wallpaper mode",
        "menu_fullscreen": "Fullscreen",
        "menu_bubble_side": "Bubble side",
        "menu_bubble_auto": "Auto",
        "menu_bubble_left": "Left",
        "menu_bubble_right": "Right",
        "menu_speech_behavior": "Speech behavior",
        "menu_speech_interrupt": "Interrupt previous",
        "menu_speech_wait": "Wait to finish",
        "menu_window_size": "Window size...",
        "menu_automation": "🤖 Automation",
        "menu_model_defaults": "Model Defaults",
        "menu_screen_reading": "Screen reading",
        "menu_enable": "Enable",
        "menu_random": "Random",
        "menu_exact": "Exact",
        "menu_minimum": "Minimum...",
        "menu_maximum": "Maximum...",
        "menu_interval": "Interval...",
        "menu_desktop_audio": "Desktop audio",
        "menu_random_speech": "Random speech",
        "menu_timer": "Timer...",
        "menu_audio_cfg": "🎤 Audio",
        "menu_mic_stt": "Microphone (STT)",
        "menu_hold_to_talk": "Hold to talk",
        "menu_mic_open": "Open microphone",
        "menu_mic_shortcut": "Microphone shortcut...",
        "menu_global_shortcut": "Global shortcut (Win+V)...",
        "menu_mic_device": "Microphone device...",
        "menu_intelligence": "🧠 Intelligence",
        "menu_ai_enable": "AI Enabled",
        "menu_ai_provider": "AI Provider",
        "menu_provider_auto": "Automatic",
        "menu_provider_groq": "Groq (free)",
        "menu_provider_gemini": "Gemini (Google)",
        "menu_provider_hf": "API (Hugging Face)",
        "menu_provider_ollama": "Ollama (local)",
        "menu_provider_phrases": "Preset phrases",
        "menu_configure_gemini": "Configure Gemini...",
        "menu_configure_groq": "Configure Groq...",
        "menu_configure_hf": "Configure HuggingFace...",
        "menu_ollama_model": "Ollama Model",
        "menu_permissions": "Permissions",
        "menu_perm_read_file": "Read files",
        "menu_perm_list_files": "List folders",
        "menu_perm_run_command": "Run commands",
        "menu_perm_write_file": "Write files",
        "menu_perm_screenshot": "Take screenshot",
        "menu_perm_open_url": "Open URLs",
        "menu_perm_listen": "Listen to desktop sounds",
        "menu_profile": "👤 My Profile...",
        "menu_about": "ℹ About",
        "menu_clear_history": "Clear History",
        "menu_quit": "Quit",
        "menu_language": "🌐 Language",
        "about_comments": "A virtual pet by Kasane Teto",
        "profile_name_label": "Your name:",
        "profile_name_placeholder": "Ex: John, Jane...",
        "profile_bio_label": "Extra details (optional):",
        "profile_bio_placeholder": "Ex: pronouns, age, nickname...",
        "gemini_entry_placeholder": "Paste your Gemini key here...",
        "groq_entry_placeholder": "Paste your Groq key here...",
        "hf_entry_placeholder": "Paste your HuggingFace token here...",
        "gemini_link_label": "Open Google AI Studio",
        "groq_link_label": "Open Groq Console",
        "hf_link_label": "Open HuggingFace Tokens",
        "stt_shortcut_placeholder": "Press a key",
        "alarm_toggle_label": "Enabled",
        "alarm_delete_label": "Delete",
        "alarm_stopped": "Alarm turned off! ^_^",
        "alarm_deleted_msg": "Alarm removed!",
        "alarm_added_msg": "Alarm added! 💃",
        "menu_tts": "Assistant Voice",
        "menu_mic_mode": "Microphone mode",
        "menu_tts_provider": "Voice Provider",
        "tts_provider_auto": "Automatic",
        "tts_provider_fish": "Fish Audio",
        "tts_provider_edge": "Edge-TTS",
        "tts_provider_pyttsx": "pyttsx3",
        "menu_tts_device": "Output device...",
        "menu_tts_volume": "Voice volume",
        "tts_volume_title": "Voice Volume",
        "tts_volume_label": "Volume level (0-100):",
        "tts_device_title": "Audio Device",
        "tts_device_label": "Choose output device:",
        "no_tts_device": "No device found!",
        "menu_shortcuts": "Shortcuts",
        "menu_configure_fish": "Configure Fish Audio...",
        "fish_setup_title": "Configure Fish Audio",
        "fish_key_placeholder": "Paste your Fish Audio key here...",
        "fish_voice_placeholder": "Voice ID (optional)",
        "fish_configured": "Fish Audio configured! ^_^",
        "fish_no_key": "No key pasted...",
        "lang_pt": "Portuguese",
        "lang_en": "English",
        "lang_jp": "Japanese",
        "menu_voice": "🎤 Voice",
        "menu_microphone": "🎧 Microphone",
        "settings_window": "Window",
        "settings_appearance_desc": "Here you customize your new addiction's looks.",
        "settings_bubble": "Speech Bubble",
        "settings_model": "Model",
        "settings_language": "Language",
        "settings_voice_section": "Assistant Voice",
        "settings_voice_provider_section": "Voice Provider",
        "settings_fish_section": "Fish Audio",
        "settings_mic_section": "Microphone (STT)",
        "settings_mic_mode_section": "Operation Mode",
        "settings_shortcuts_section": "Shortcuts",
        "settings_ai_section": "Artificial Intelligence",
        "settings_ai_provider_section": "AI Provider",
        "settings_api_keys_section": "API Keys",
        "settings_ollama_section": "Ollama (local)",
        "settings_profile_section": "Profile",
        "settings_permissions_section": "Permissions",
        "settings_screen_reading_section": "Screen Reading",
        "settings_audio_section": "Desktop Audio",
        "settings_speech_section": "Random Speech",
        "settings_speak_section": "Speak Now",
        "settings_alarms_section": "Alarms",
        "settings_about_section": "About",
        "settings_credits_section": "Acknowledgements",
        "settings_voice_title": "Voice Title",
        "settings_model_defaults_section": "Model Defaults",
        "settings_bubble_desc": "Where and how the pet throws its speech.",
        "settings_model_desc": "Change the pet's outfit. It has more variety than your wardrobe.",
        "settings_language_desc": "Change the language. The pet is multilingual, unlike you.",
        "settings_language_restart": "Português, English or 日本語. Requires restart.",
        "settings_model_item_desc": "Each model comes with sprites, phrases, and a unique style.",
        "settings_voice_desc": "For when you want to hear nonsense out loud.",
        "settings_voice_provider_choose": "Who will lend their voice to your pet.",
        "settings_output_device_desc": "Which sound card will moan the pet's phrases.",
        "settings_fish_desc": "For those who want voice actor quality but have a snack budget.",
        "settings_mic_desc": "For you to talk to the pet. No, it won't judge you. Lie, it will.",
        "settings_mic_mode_desc": "How to activate the microphone. Choose wisely (or not).",
        "settings_shortcuts_desc": "Magic keys to activate the microphone.",
        "settings_ai_desc": "The pet's brain. Disable if you want a dumb but happy pet.",
        "settings_ai_provider_desc": "Choose your favorite hallucination source.",
        "settings_api_keys_desc": "The magic key that unlocks the pet's powers (and maybe your credit card).",
        "settings_ollama_desc": "AI running on your PC. Provider for the paranoid (read: sensible).",
        "settings_profile_desc": "Teach your pet to call you by name. Or 'boss'. Or 'broke-ass'.",
        "settings_permissions_desc": "Letting the AI read your files is like giving your Wi-Fi password to your neighbor.",
        "settings_screen_reading_desc": "The pet peeks at your screen and comments. Gossip mode ON.",
        "settings_audio_desc": "The pet listens to PC sounds. Like your mom when you're in your room.",
        "settings_speech_desc": "The pet speaks out of nowhere. Like your intrusive thoughts at 3 AM.",
        "settings_speak_desc": "Makes the pet speak after X seconds. Like an alarm, but cuter.",
        "settings_alarms_desc": "Create alarms for the pet to remind you of things. Like your conscience, but cuter.",
        "settings_about_subtitle": "A virtual desktop pet with integrated AI.",
        "settings_created_by": "Created by",
        "settings_original_char": "Original Character",
        "settings_technologies": "Technologies",
        "settings_credits_text": "Thank you for using Mate Helper! This project is open source and made with love (and coffee). Contributions are welcome! ❤️",
        "settings_no_alarms": "No alarms configured. Are you disorganized or just don't care?",
        "settings_configure_fish": "Configure Fish Audio...",
        "settings_edit_profile": "Edit profile...",
        "settings_open_timer": "Open timer...",
        "settings_add_alarm_btn": "Add alarm...",
        "settings_configure_shortcut": "Configure shortcut...",
        "settings_global_help": "Help: Win+V...",
        "settings_new_alarm": "New alarm",
        "settings_always_on_top_desc": "Keeps the pet always visible. Like your anxiety.",
        "settings_wallpaper_desc": "Pet fills the whole screen. Perfect for streaming or pretending you have friends.",
        "settings_pet_size_desc": "From 3 to 10. At 10 it's the size of your bills.",
        "settings_bubble_side_desc": "Which side the bubble appears. Like politics, but without drama.",
        "settings_speech_behavior_desc": "Interrupt like your mom or wait like your Wi-Fi.",
        "settings_voice_enable_desc": "The pet speaks messages out loud. Like a radio announcer, but cuter.",
        "settings_voice_provider_desc": "Fish Audio has cinematic voices (but costs an arm and a leg). Edge-TTS is free.",
        "settings_voice_volume_desc": "0 = mute (finally, peace). 100 = your neighbor knocks on the door.",
        "settings_fish_configure_desc": "Open the dialog to configure your key and choose the voice.",
        "settings_mic_enable_desc": "When enabled, you can talk nonsense to the pet.",
        "settings_mic_mode_choose_desc": "Hold to talk = walkie-talkie. Open = your mom listening to everything.",
        "settings_mic_device_desc": "Which microphone will capture your voice (and your secrets).",
        "settings_mic_shortcut_desc": "Key used for Press-to-Talk (when the app is focused).",
        "settings_global_shortcut_desc": "Win+V works from anywhere. Like a stalker, but with purpose.",
        "settings_ai_enabled_desc": "When off, only preset phrases. It's like having a real pet: cute, but limited.",
        "settings_ai_provider_choose_desc": "Auto tries Groq (free), Gemini, HuggingFace and finally preset phrases. Order: luck.",
        "settings_gemini_btn_desc": "Generous free plan (60 req/min). Google loves you (and your data).",
        "settings_groq_btn_desc": "100% free and very fast. ~600 req/day. The king of cost-benefit.",
        "settings_hf_btn_desc": "Free inference with read token. Open-source vibes.",
        "settings_ollama_model_desc": "AI model installed locally. Nothing goes to the cloud. Not even your secrets.",
        "settings_profile_btn_desc": "Name and details for the pet to know you better (or mock you).",
        "settings_model_defaults_desc": "When enabled, uses the intervals that came with the model. It's like eating what you're given.",
        "settings_screen_enable_desc": "Captures the screen and the pet comments on what it sees. You know that feeling of being watched?",
        "settings_screen_mode_desc": "Random: interval varies. Exact: like Brazilian punctuality (never).",
        "settings_spin_min_desc": "Minimum time between gossips.",
        "settings_spin_max_desc": "Maximum time between gossips.",
        "settings_spin_exact_desc": "Fixed time. Like a soap opera: always at the same time.",
        "settings_audio_enable_desc": "Records system audio and the pet comments. Gossip in stereo.",
        "settings_audio_mode_desc": "Random: it listens when it wants. Exact: it LISTENS.",
        "settings_spin_audio_min_desc": "Minimum between audio gossips.",
        "settings_spin_audio_max_desc": "Maximum between audio gossips.",
        "settings_spin_audio_exact_desc": "Fixed time between gossips. Like a weather forecast.",
        "settings_speech_enable_desc": "The pet blurts out spontaneous phrases. Because silence is awkward.",
        "settings_speech_mode_desc": "Random: it speaks when it wants. Exact: like a scheduled meeting.",
        "settings_spin_speech_min_desc": "Minimum between intrusive thoughts.",
        "settings_spin_speech_max_desc": "Maximum between intrusive thoughts.",
        "settings_spin_speech_exact_desc": "Fixed interval. Like the tax inspector coming every month.",
        "settings_speech_timer_desc": "Set a timer for the pet to speak. Useful to remind you to get up (or not).",
        "settings_new_alarm_desc": "Creates a new alarm. No, it won't actually wake you up. Maybe.",
        "settings_gemini_label": "Gemini (Google)",
        "settings_groq_label": "Groq",
        "settings_hf_label": "HuggingFace",
        "settings_pet_size_scale": "From 3 to 10. At 10 it's the size of your bills.",
        "settings_spin_min_label": "Minimum interval (s)",
        "settings_spin_max_label": "Maximum interval (s)",
        "settings_spin_exact_label": "Exact interval (s)",
        "system_default": "System default",
        "enable_microphone": "Enable microphone",
        "settings_mic_mode": "Mode",
        "settings_mic_device": "Device",
        "settings_my_profile": "My Profile",
        "settings_speech_timer": "Speech Timer",
        "settings_api_key": "API Key",
    },
    "jp": {
        "greeting": "やあ！会えて嬉しいよ！ ^_^",
        "ollama_started": "Ollama起動！おしゃべりできるよ！ ^_^",
        "ollama_not_found": "うーん、Ollamaが見つからない… 定型文を使うね！",
        "history_cleared": "履歴を消したよ！ ^_^",
        "no_mic_found": "マイクが見つかりません！",
        "mic_configured": "マイクを設定したよ！ ^_^",
        "gemini_configured": "Geminiを設定したよ！GoogleのAIを使うね！ ^_^",
        "gemini_no_key": "キーが貼られてないよ… もう一度試して！",
        "groq_configured": "Groqを設定したよ！最速のAIを使うね！ ^_^",
        "groq_no_key": "キーが貼られてないよ… もう一度試して！",
        "hf_configured": "HuggingFaceを設定したよ！コミュニティのAIを使うね！ ^_^",
        "hf_no_token": "トークンが貼られてないよ… もう一度試して！",
        "profile_saved_name": "わかった！これから{name}って呼ぶね！ ^_^",
        "profile_saved": "プロフィールを更新したよ！ ^_^",
        "restarting_model": "{model}を読み込むために再起動するね…",
        "alarm_stopped_generic": "アラームの時間だよ！ 🎵",
        "alarm_stopped_msg": "アラームを止めたよ！ ^_^",
        "alarm_deleted": "アラームを削除したよ！",
        "alarm_added": "アラームを追加したよ！ 💃",
        "speech_timer_title": "発話タイマー",
        "accessibility_interval_title": "自動読み上げ間隔",
        "accessibility_min_title": "読み上げ最小間隔",
        "accessibility_max_title": "読み上げ最大間隔",
        "audio_interval_title": "音声文字起こし間隔",
        "audio_min_title": "音声最小間隔",
        "audio_max_title": "音声最大間隔",
        "speech_min_title": "発話最小間隔",
        "speech_max_title": "発話最大間隔",
        "speech_exact_title": "発話の正確な間隔",
        "window_scale_title": "ウィンドウサイズ",
        "mic_device_title": "マイクデバイス",
        "global_shortcut_title": "グローバルショートカット (Win+V)",
        "stt_shortcut_title": "マイクショートカット",
        "gemini_setup_title": "Geminiの設定",
        "groq_setup_title": "Groqの設定",
        "hf_setup_title": "HuggingFaceの設定",
        "profile_title": "マイプロフィール",
        "add_alarm_title": "アラーム追加",
        "speech_timer_label": "何秒後にペットに話させますか？",
        "accessibility_interval_label": "何秒ごとに画面を読み上げますか？",
        "accessibility_min_label": "読み上げの最小秒数は？",
        "accessibility_max_label": "読み上げの最大秒数は？",
        "audio_interval_label": "何秒ごとに音声を文字起こししますか？",
        "audio_min_label": "文字起こしの最小秒数は？",
        "audio_max_label": "文字起こしの最大秒数は？",
        "speech_min_label": "ランダム発話の最小秒数は？",
        "speech_max_label": "ランダム発話の最大秒数は？",
        "speech_exact_label": "何秒ごとにペットに話させますか？",
        "window_scale_label": "ペットのウィンドウサイズを調整：",
        "window_scale_default_mark": "デフォルト",
        "mic_device_label": "入力デバイスを選んで：",
        "mic_choose_device": "マイクデバイス",
        "btn_cancel": "キャンセル",
        "btn_ok": "OK",
        "btn_save": "保存",
        "btn_add": "追加",
        "global_shortcut_markup": "<b>グローバルショートカット：Win + V</b>\n\n<b>Win+V</b>ショートカットを使うと、アプリにフォーカスがなくても画面のどこからでもプッシュトークが使えます。\n\n使うには、コンポジターのショートカットファイルに\n次の行を追加してください：\n\n<tt><span size=\"smaller\">Mod+V  {{ spawn-sh \"bash {path} toggle\"; }}</span></tt>\n\nまたは手動で実行：\n<tt><span size=\"smaller\">bash {path} press   # 録音開始\nbash {path} release # 録音停止\nbash {path} toggle  # オン/オフ切替</span></tt>",
        "stt_shortcut_markup": "<b>プッシュトークのショートカット</b>\n\nこのキーはアプリにフォーカスがあるときに機能します。\n画面のどこからでも使うには\n<b>Win+V</b>（グローバルショートカット）を使ってください。\n\n下のフィールドで希望のキーを押してください。\n押している間録音、離すと文字起こしします。\n\n現在：<b>{current}</b>",
        "gemini_markup": "<b>Gemini APIキー</b>\n\nGeminiには generous な無料プランがあります（60 req/min）。\n\n1. アクセス：https://aistudio.google.com/apikey\n2. 「Create API Key」をクリック\n3. キーをコピーして下に貼り付け\n\nクレジットカードは不要です。",
        "groq_markup": "<b>Groq APIキー</b>\n\nGroqは100％無料でとっても速い！\n独自GPU（LPU）を使ってLlama 3、Gemma、Mixtralを実行します。\n\n1. アクセス：https://console.groq.com/keys\n2. 「Create API Key」をクリック\n3. キーをコピーして下に貼り付け\n\nクレジットカード不要。約600 req/日無料！",
        "hf_markup": "<b>HuggingFace APIトークン</b>\n\nHuggingFaceはトークンで無料推論を提供！\nDialoGPTなどのモデルを使って会話できます。\n\n1. アクセス：https://huggingface.co/settings/tokens\n2. 「New token」をクリック\n3. 「read」権限を選んでトークンをコピー\n4. 下に貼り付け\n\n無料、クレジットカード不要！",
        "profile_markup": "<b>AIがあなたをどう呼ぶか</b>\n\nこのデータはローカルに保存され、\nAIがあなたをよりよく知るためだけに使われます。",
        "add_alarm_markup": "<b>新しいアラーム</b>\n\n時間を選んでね。いくつでも作れるよ！",
        "add_alarm_name_placeholder": "例：起床、昼食、薬…",
        "add_alarm_hour_label": "時：",
        "add_alarm_min_label": "分：",
        "add_alarm_name_label": "名前（任意）：",
        "menu_chat": "会話",
        "menu_alarm": "アラーム",
        "menu_add_alarm": "アラーム追加...",
        "menu_stop_alarm": "アラーム停止",
        "menu_model": "ペットのモデル",
        "menu_settings": "設定",
        "menu_appearance": "🖥 外観",
        "menu_always_on_top": "常に最前面",
        "menu_wallpaper": "壁紙モード",
        "menu_fullscreen": "フルスクリーン",
        "menu_bubble_side": "吹き出しの位置",
        "menu_bubble_auto": "自動",
        "menu_bubble_left": "左",
        "menu_bubble_right": "右",
        "menu_speech_behavior": "発話動作",
        "menu_speech_interrupt": "前を中断",
        "menu_speech_wait": "終了を待つ",
        "menu_window_size": "ウィンドウサイズ...",
        "menu_automation": "🤖 自動化",
        "menu_model_defaults": "モデルのデフォルト",
        "menu_screen_reading": "画面読み上げ",
        "menu_enable": "有効",
        "menu_random": "ランダム",
        "menu_exact": "正確",
        "menu_minimum": "最小...",
        "menu_maximum": "最大...",
        "menu_interval": "間隔...",
        "menu_desktop_audio": "デスクトップ音声",
        "menu_random_speech": "ランダム発話",
        "menu_timer": "タイマー...",
        "menu_audio_cfg": "🎤 オーディオ",
        "menu_mic_stt": "マイク (STT)",
        "menu_hold_to_talk": "プッシュトーク",
        "menu_mic_open": "マイク開放",
        "menu_mic_shortcut": "マイクショートカット...",
        "menu_global_shortcut": "グローバルショートカット (Win+V)...",
        "menu_mic_device": "マイクデバイス...",
        "menu_intelligence": "🧠 インテリジェンス",
        "menu_ai_enable": "AI有効",
        "menu_ai_provider": "AIプロバイダー",
        "menu_provider_auto": "自動",
        "menu_provider_groq": "Groq（無料）",
        "menu_provider_gemini": "Gemini（Google）",
        "menu_provider_hf": "API（Hugging Face）",
        "menu_provider_ollama": "Ollama（ローカル）",
        "menu_provider_phrases": "定型文",
        "menu_configure_gemini": "Geminiを設定...",
        "menu_configure_groq": "Groqを設定...",
        "menu_configure_hf": "HuggingFaceを設定...",
        "menu_ollama_model": "Ollamaモデル",
        "menu_permissions": "権限",
        "menu_perm_read_file": "ファイル読み取り",
        "menu_perm_list_files": "フォルダ一覧表示",
        "menu_perm_run_command": "コマンド実行",
        "menu_perm_write_file": "ファイル書き込み",
        "menu_perm_screenshot": "スクリーンショット撮影",
        "menu_perm_open_url": "URLを開く",
        "menu_perm_listen": "デスクトップ音声を聴く",
        "menu_profile": "👤 マイプロフィール...",
        "menu_about": "ℹ について",
        "menu_clear_history": "履歴を消去",
        "menu_quit": "終了",
        "menu_language": "🌐 言語",
        "about_comments": "Kasane Tetoによるバーチャルペット",
        "profile_name_label": "あなたの名前：",
        "profile_name_placeholder": "例：太郎、花子...",
        "profile_bio_label": "追加情報（任意）：",
        "profile_bio_placeholder": "例：代名詞、年齢、ニックネーム...",
        "gemini_entry_placeholder": "Geminiキーをここに貼り付け...",
        "groq_entry_placeholder": "Groqキーをここに貼り付け...",
        "hf_entry_placeholder": "HuggingFaceトークンをここに貼り付け...",
        "gemini_link_label": "Google AI Studioを開く",
        "groq_link_label": "Groq Consoleを開く",
        "hf_link_label": "HuggingFace Tokensを開く",
        "stt_shortcut_placeholder": "キーを押してください",
        "alarm_toggle_label": "有効",
        "alarm_delete_label": "削除",
        "alarm_stopped": "アラームを止めたよ！ ^_^",
        "alarm_deleted_msg": "アラームを削除したよ！",
        "alarm_added_msg": "アラームを追加したよ！ 💃",
        "menu_tts": "アシスタント音声",
        "menu_mic_mode": "マイクモード",
        "menu_tts_provider": "音声プロバイダ",
        "tts_provider_auto": "自動",
        "tts_provider_fish": "Fish Audio",
        "tts_provider_edge": "Edge-TTS",
        "tts_provider_pyttsx": "pyttsx3",
        "menu_tts_device": "出力デバイス...",
        "menu_tts_volume": "音量",
        "tts_volume_title": "音量設定",
        "tts_volume_label": "音量レベル (0-100):",
        "tts_device_title": "オーディオデバイス",
        "tts_device_label": "出力デバイスを選択：",
        "no_tts_device": "デバイスが見つかりません！",
        "menu_shortcuts": "ショートカット",
        "menu_configure_fish": "Fish Audio設定...",
        "fish_setup_title": "Fish Audio設定",
        "fish_key_placeholder": "Fish Audioキーを貼り付け...",
        "fish_voice_placeholder": "音声ID（任意）",
        "fish_configured": "Fish Audio設定完了！^_^",
        "fish_no_key": "キーが貼り付けられていません...",
        "lang_pt": "ポルトガル語",
        "lang_en": "英語",
        "lang_jp": "日本語",
        "menu_voice": "🎤 音声",
        "menu_microphone": "🎧 マイク",
        "settings_window": "ウィンドウ",
        "settings_appearance_desc": "ここであなたの新しい中毒の見た目をカスタマイズできます。",
        "settings_bubble": "吹き出し",
        "settings_model": "モデル",
        "settings_language": "言語",
        "settings_voice_section": "アシスタント音声",
        "settings_voice_provider_section": "音声プロバイダー",
        "settings_fish_section": "Fish Audio",
        "settings_mic_section": "マイク (STT)",
        "settings_mic_mode_section": "動作モード",
        "settings_shortcuts_section": "ショートカット",
        "settings_ai_section": "人工知能",
        "settings_ai_provider_section": "AIプロバイダー",
        "settings_api_keys_section": "APIキー",
        "settings_ollama_section": "Ollama（ローカル）",
        "settings_profile_section": "プロフィール",
        "settings_permissions_section": "権限",
        "settings_screen_reading_section": "画面読み上げ",
        "settings_audio_section": "デスクトップ音声",
        "settings_speech_section": "ランダム発話",
        "settings_speak_section": "今すぐ話す",
        "settings_alarms_section": "アラーム",
        "settings_about_section": "バージョン情報",
        "settings_credits_section": "謝辞",
        "settings_voice_title": "音声のタイトル",
        "settings_model_defaults_section": "モデルのデフォルト",
        "settings_bubble_desc": "ペットがどこでどうやって吹き出しを表示するか。",
        "settings_model_desc": "ペットの着せ替え。あなたのクローゼットよりバリエーション豊か。",
        "settings_language_desc": "言語を変更。ペットはあなたと違って多言語話者です。",
        "settings_language_restart": "Português、Englishまたは日本語。再起動が必要です。",
        "settings_model_item_desc": "各モデルにはスプライト、フレーズ、独自のスタイルが付いてきます。",
        "settings_voice_desc": "適当なことを声に出して聞きたいときに。",
        "settings_voice_provider_choose": "ペットに声を貸してくれるサービス。",
        "settings_output_device_desc": "どのサウンドカードがペットのフレーズを再生するか。",
        "settings_fish_desc": "声優クオリティの声が欲しいけど予算は駄菓子級って人に。",
        "settings_mic_desc": "ペットと話すためのマイク。いや、君のことジャッジしないよ。うそ、するよ。",
        "settings_mic_mode_desc": "マイクの起動方法。賢く選んでね（選ばなくてもいいけど）。",
        "settings_shortcuts_desc": "マイクを起動する魔法のキー。",
        "settings_ai_desc": "ペットの脳みそ。オフにするとバカだけど幸せなペットになります。",
        "settings_ai_provider_desc": "お気に入りの幻覚生成源を選んでください。",
        "settings_api_keys_desc": "ペットのパワー（そしてたぶん君のクレジットカード）を解き放つ魔法の鍵。",
        "settings_ollama_desc": "PC上で動くAI。パラノイア向けプロバイダー（つまり賢い人）。",
        "settings_profile_desc": "ペットにあなたの名前を教える。「社長」でも「ヒモ」でも。",
        "settings_permissions_desc": "AIにファイルを読ませるのは、Wi-Fiパスワードを隣人に教えるようなもの。",
        "settings_screen_reading_desc": "ペットが画面を覗き見してコメントする。ゴシップモードON。",
        "settings_audio_desc": "ペットがPCの音を聞く。部屋にいる時のお母さんみたいに。",
        "settings_speech_desc": "ペットが突然しゃべり出す。午前3時の侵入思考みたいに。",
        "settings_speak_desc": "X秒後にペットに話させる。アラームより可愛いやつ。",
        "settings_alarms_desc": "ペットが色々思い出させてくれるアラームを作成。良心より可愛い。",
        "settings_about_subtitle": "AI統合デスクトップペット。",
        "settings_created_by": "作成者",
        "settings_original_char": "オリジナルキャラクター",
        "settings_technologies": "使用技術",
        "settings_credits_text": "Mate Helperをお使いいただきありがとうございます！このプロジェクトはオープンソースで、愛情とコーヒーで作られています。コントリビューション大歓迎！❤️",
        "settings_no_alarms": "アラームが設定されていません。整理整頓ができないだけ？それともどうでもいいの？",
        "settings_configure_fish": "Fish Audio設定...",
        "settings_edit_profile": "プロフィール編集...",
        "settings_open_timer": "タイマーを開く...",
        "settings_add_alarm_btn": "アラーム追加...",
        "settings_configure_shortcut": "ショートカット設定...",
        "settings_global_help": "ヘルプ: Win+V...",
        "settings_new_alarm": "新しいアラーム",
        "settings_always_on_top_desc": "ペットを常に最前面に表示。君の不安みたいに。",
        "settings_wallpaper_desc": "ペットが画面全体に。配信や友達がいるふりに最適。",
        "settings_pet_size_desc": "3から10まで。10にすると請求書のサイズになります。",
        "settings_bubble_side_desc": "吹き出しを表示する側。政治みたいだけど揉めない。",
        "settings_speech_behavior_desc": "お母さんみたく遮るか、Wi-Fiみたく待つか。",
        "settings_voice_enable_desc": "ペットがメッセージを音読する。ラジオのアナウンサーより可愛い。",
        "settings_voice_provider_desc": "Fish Audioは映画品質（でも高額）。Edge-TTSは無料。",
        "settings_voice_volume_desc": "0 = ミュート（やっと平和）。100 = 隣人がドアを叩く。",
        "settings_fish_configure_desc": "キー設定と音声選択のダイアログを開く。",
        "settings_mic_enable_desc": "有効にすると、ペットに向かって適当なことを言えます。",
        "settings_mic_mode_choose_desc": "押して話す = トランシーバー。開放 = 全部聞かれてるお母さん。",
        "settings_mic_device_desc": "どのマイクがあなたの声（と秘密）をキャプチャするか。",
        "settings_mic_shortcut_desc": "プッシュトークに使うキー（アプリにフォーカスがあるとき）。",
        "settings_global_shortcut_desc": "Win+Vはどこでも使える。ストーカーだけど目的あり。",
        "settings_ai_enabled_desc": "オフにすると定型文のみ。本物のペットみたいに可愛いけど限定的。",
        "settings_ai_provider_choose_desc": "自動はGroq（無料）、Gemini、HuggingFace、最後に定型文を試す。順序は運任せ。",
        "settings_gemini_btn_desc": "太っ腹な無料プラン（60 req/min）。Googleは君（と君のデータ）を愛してる。",
        "settings_groq_btn_desc": "100%無料で超高速。約600 req/日。コスパの王者。",
        "settings_hf_btn_desc": "読み取りトークンで無料推論。オープンソースの良さ。",
        "settings_ollama_model_desc": "ローカルにインストールされたAIモデル。クラウドには何も行かない。秘密もね。",
        "settings_profile_btn_desc": "ペットがあなたをよく知る（またはからかう）ための名前と詳細。",
        "settings_model_defaults_desc": "有効にすると、モデル付属の間隔を使う。与えられたものを食べる感じ。",
        "settings_screen_enable_desc": "画面をキャプチャしてペットが見たものにコメントする。見られてる気がするあの感覚？",
        "settings_screen_mode_desc": "ランダム：間隔が変動。正確：ブラジル人の時間厳守みたいに（絶対ない）。",
        "settings_spin_min_desc": "ゴシップの最小間隔。",
        "settings_spin_max_desc": "ゴシップの最大間隔。",
        "settings_spin_exact_desc": "固定時間。テレビドラマみたいに毎回同じ時間。",
        "settings_audio_enable_desc": "システム音声を録音してペットがコメントする。ステレオゴシップ。",
        "settings_audio_mode_desc": "ランダム：聞きたい時に聞く。正確：確実に聞く。",
        "settings_spin_audio_min_desc": "音声ゴシップの最小間隔。",
        "settings_spin_audio_max_desc": "音声ゴシップの最大間隔。",
        "settings_spin_audio_exact_desc": "ゴシップの固定間隔。天気予報みたいに。",
        "settings_speech_enable_desc": "ペットが突然フレーズを言う。沈黙は気まずいからね。",
        "settings_speech_mode_desc": "ランダム：言いたい時に言う。正確：予定された会議みたいに。",
        "settings_spin_speech_min_desc": "侵入思考の最小間隔。",
        "settings_spin_speech_max_desc": "侵入思考の最大間隔。",
        "settings_spin_speech_exact_desc": "固定間隔。税金調査官が毎月来るみたいに。",
        "settings_speech_timer_desc": "ペットが話すタイマーを設定。立ち上がるのを思い出させるのに便利（そうでもないかも）。",
        "settings_new_alarm_desc": "新しいアラームを作成。実際に起こしてはくれないよ。たぶん。",
        "settings_gemini_label": "Gemini（Google）",
        "settings_groq_label": "Groq",
        "settings_hf_label": "HuggingFace",
        "settings_pet_size_scale": "3から10まで。10にすると請求書のサイズになります。",
        "settings_spin_min_label": "最小間隔（秒）",
        "settings_spin_max_label": "最大間隔（秒）",
        "settings_spin_exact_label": "固定間隔（秒）",
        "system_default": "システム既定",
        "enable_microphone": "マイクを有効にする",
        "settings_mic_mode": "モード",
        "settings_mic_device": "デバイス",
        "settings_my_profile": "マイプロフィール",
        "settings_speech_timer": "スピーチタイマー",
        "settings_api_key": "APIキー",
    },
}
