STRINGS = {
    "pt": {
        "greeting": "Oii! Que bom te ver! ^_^",
        "ollama_started": "Ollama ligado! Tô pronta pra conversar! ^_^",
        "ollama_not_found": "Hmm, não achei o Ollama... Vou usar frases prontas mesmo!",
        "history_cleared": "Histórico limpo! ^_^",
        "no_mic_found": "Nenhum microfone encontrado!",
        "mic_configured": "Microfone configurado! ^_^",
        "gemini_configured": "Gemini configurado! Vou usar IA do Google! ^_^",
        "gemini_no_key": "Não colou nenhuma chave... Tenta de novo!",
        "groq_configured": "Groq configurado! Vou usar a IA mais rápida! ^_^",
        "groq_no_key": "Não colou nenhuma chave... Tenta de novo!",
        "hf_configured": "HuggingFace configurado! Agora vou usar a IA da comunidade! ^_^",
        "hf_no_token": "Não colou nenhum token... Tenta de novo!",
        "profile_saved_name": "Anotado! Vou te chamar de {name} agora! ^_^",
        "profile_saved": "Perfil atualizado! ^_^",
        "restarting_model": "Reiniciando pra carregar {model}...",
        "alarm_stopped_generic": "Hora do alarme! 🎵",
        "alarm_stopped_msg": "Alarme desligado! ^_^",
        "alarm_deleted": "Alarme removido!",
        "alarm_added": "Alarme adicionado! 💃",
        "speech_timer_title": "Timer de fala",
        "accessibility_interval_title": "Intervalo da leitura automática",
        "accessibility_min_title": "Mínimo entre leituras",
        "accessibility_max_title": "Máximo entre leituras",
        "audio_interval_title": "Intervalo da transcrição de áudio",
        "audio_min_title": "Mínimo entre áudios",
        "audio_max_title": "Máximo entre áudios",
        "speech_min_title": "Intervalo mínimo entre falas",
        "speech_max_title": "Intervalo máximo entre falas",
        "speech_exact_title": "Intervalo exato entre falas",
        "window_scale_title": "Tamanho da Janela",
        "mic_device_title": "Dispositivo do Microfone",
        "global_shortcut_title": "Atalho Global (Win+V)",
        "stt_shortcut_title": "Atalho do Microfone",
        "gemini_setup_title": "Configurar Gemini",
        "groq_setup_title": "Configurar Groq",
        "hf_setup_title": "Configurar HuggingFace",
        "profile_title": "Meu Perfil",
        "add_alarm_title": "Adicionar Alarme",
        "speech_timer_label": "Daqui a quantos segundos o pet deve falar?",
        "accessibility_interval_label": "A cada quantos segundos a tela deve ser lida?",
        "accessibility_min_label": "Segundos mínimo entre leituras?",
        "accessibility_max_label": "Segundos máximo entre leituras?",
        "audio_interval_label": "A cada quantos segundos o áudio deve ser transcrito?",
        "audio_min_label": "Segundos mínimo entre transcrições?",
        "audio_max_label": "Segundos máximo entre transcrições?",
        "speech_min_label": "Segundos mínimo entre falas aleatórias?",
        "speech_max_label": "Segundos máximo entre falas aleatórias?",
        "speech_exact_label": "A cada quantos segundos o pet deve falar?",
        "window_scale_label": "Ajuste o tamanho da janela do pet:",
        "window_scale_default_mark": "Padrão",
        "mic_device_label": "Escolha o dispositivo de entrada:",
        "mic_choose_device": "Dispositivo do Microfone",
        "btn_cancel": "Cancelar",
        "btn_ok": "Ok",
        "btn_save": "Salvar",
        "btn_add": "Adicionar",
        "global_shortcut_markup": "<b>Atalho Global: Win + V</b>\n\nO atalho <b>Win+V</b> permite usar o pressionar pra falar de qualquer lugar da tela, mesmo com o app sem foco.\n\nPara funcionar, adicione esta linha ao seu\narquivo de atalhos do compositor:\n\n<tt><span size=\"smaller\">Mod+V  {{ spawn-sh \"bash {path} toggle\"; }}</span></tt>\n\nOu execute manualmente:\n<tt><span size=\"smaller\">bash {path} press   # inicia gravação\nbash {path} release # para gravação\nbash {path} toggle  # alterna liga/desliga</span></tt>",
        "stt_shortcut_markup": "<b>Atalho para Pressionar pra Falar</b>\n\nEssa tecla funciona quando o app está em foco.\nUse <b>Win+V</b> (atalho global) para funcionar\nde qualquer lugar da tela.\n\nPressione a tecla desejada no campo abaixo.\nSegure para gravar, solte para transcrever.\n\nAtual: <b>{current}</b>",
        "gemini_markup": "<b>Gemini API Key</b>\n\nO Gemini tem um plano gratuito generoso (60 req/min).\n\n1. Acesse: https://aistudio.google.com/apikey\n2. Clique em \"Criar chave de API\"\n3. Copie a chave e cole abaixo\n\nNão precisa de cartão de crédito.",
        "groq_markup": "<b>Groq API Key</b>\n\nGroq é 100% gratuito e MUITO rápido!\nUsa GPU própria (LPU) pra rodar Llama 3, Gemma e Mixtral.\n\n1. Acesse: https://console.groq.com/keys\n2. Clique em \"Create API Key\"\n3. Copie a chave e cole abaixo\n\nNão precisa de cartão de crédito. ~600 req/dia grátis!",
        "hf_markup": "<b>HuggingFace API Token</b>\n\nHuggingFace oferece inferência grátis com token!\nUse modelos como DialoGPT para conversar.\n\n1. Acesse: https://huggingface.co/settings/tokens\n2. Clique em \"New token\"\n3. Escolha permissão \"read\" e copie o token\n4. Cole abaixo\n\nGratuito, sem cartão de crédito!",
        "profile_markup": "<b>Como a IA deve te tratar</b>\n\nEsses dados são salvos localmente e usados\napenas para a IA te conhecer melhor.",
        "add_alarm_markup": "<b>Novo Alarme</b>\n\nEscolha o horário. Pode criar quantos quiser!",
        "add_alarm_name_placeholder": "Ex: Acordar, Almoço, Remédio...",
        "add_alarm_hour_label": "Hora:",
        "add_alarm_min_label": "Min:",
        "add_alarm_name_label": "Nome (opcional):",
        "menu_chat": "Conversar",
        "menu_alarm": "Alarme",
        "menu_add_alarm": "Adicionar alarme...",
        "menu_stop_alarm": "Parar Alarme",
        "menu_model": "Modelo do pet",
        "menu_settings": "Configurações",
        "menu_appearance": "🖥 Aparência",
        "menu_always_on_top": "Sempre no topo",
        "menu_wallpaper": "Modo papel de parede",
        "menu_fullscreen": "Tela cheia",
        "menu_bubble_side": "Lado do balão",
        "menu_bubble_auto": "Automático",
        "menu_bubble_left": "Esquerda",
        "menu_bubble_right": "Direita",
        "menu_window_size": "Tamanho da janela...",
        "menu_automation": "🤖 Automação",
        "menu_model_defaults": "Padrão do Modelo",
        "menu_screen_reading": "Leitura de tela",
        "menu_enable": "Ativar",
        "menu_random": "Aleatório",
        "menu_exact": "Exato",
        "menu_minimum": "Mínimo...",
        "menu_maximum": "Máximo...",
        "menu_interval": "Intervalo...",
        "menu_desktop_audio": "Áudio do desktop",
        "menu_random_speech": "Falas aleatórias",
        "menu_timer": "Timer...",
        "menu_audio_cfg": "🎤 Áudio",
        "menu_mic_stt": "Microfone (STT)",
        "menu_hold_to_talk": "Pressionar pra falar",
        "menu_mic_open": "Microfone aberto",
        "menu_mic_shortcut": "Atalho do microfone...",
        "menu_global_shortcut": "Atalho global (Win+V)...",
        "menu_mic_device": "Dispositivo do microfone...",
        "menu_intelligence": "🧠 Inteligência",
        "menu_ai_provider": "Provedor de IA",
        "menu_provider_auto": "Automático",
        "menu_provider_groq": "Groq (grátis)",
        "menu_provider_gemini": "Gemini (Google)",
        "menu_provider_hf": "API (Hugging Face)",
        "menu_provider_ollama": "Ollama (local)",
        "menu_provider_phrases": "Frases prontas",
        "menu_configure_gemini": "Configurar Gemini...",
        "menu_configure_groq": "Configurar Groq...",
        "menu_configure_hf": "Configurar HuggingFace...",
        "menu_ollama_model": "Modelo Ollama",
        "menu_permissions": "Permissões",
        "menu_perm_read_file": "Ler arquivos",
        "menu_perm_list_files": "Listar pastas",
        "menu_perm_run_command": "Executar comandos",
        "menu_perm_write_file": "Escrever arquivos",
        "menu_perm_screenshot": "Capturar tela",
        "menu_perm_open_url": "Abrir URLs",
        "menu_perm_listen": "Escutar sons do desktop",
        "menu_profile": "👤 Meu Perfil...",
        "menu_about": "ℹ Sobre",
        "menu_clear_history": "Limpar Histórico",
        "menu_quit": "Sair",
        "menu_language": "🌐 Idioma",
        "about_comments": "Um pet virtual da Kasane Teto",
        "profile_name_label": "Seu nome:",
        "profile_name_placeholder": "Ex: João, Maria...",
        "profile_bio_label": "Detalhes extras (opcional):",
        "profile_bio_placeholder": "Ex: pronomes, idade, apelido...",
        "gemini_entry_placeholder": "Cole sua chave Gemini aqui...",
        "groq_entry_placeholder": "Cole sua chave Groq aqui...",
        "hf_entry_placeholder": "Cole seu token HuggingFace aqui...",
        "gemini_link_label": "Abrir Google AI Studio",
        "groq_link_label": "Abrir Groq Console",
        "hf_link_label": "Abrir HuggingFace Tokens",
        "stt_shortcut_placeholder": "Pressione uma tecla",
        "alarm_toggle_label": "Ativado",
        "alarm_delete_label": "Deletar",
        "alarm_stopped": "Alarme desligado! ^_^",
        "alarm_deleted_msg": "Alarme removido!",
        "alarm_added_msg": "Alarme adicionado! 💃",
        "menu_tts": "Voz do Assistente",
        "menu_mic_mode": "マイクモード",
        "menu_tts_provider": "Provedor de Voz",
        "tts_provider_auto": "Automático",
        "tts_provider_fish": "Fish Audio",
        "tts_provider_edge": "Edge-TTS",
        "tts_provider_pyttsx": "pyttsx3",
        "menu_tts_device": "Dispositivo de saída...",
        "tts_device_title": "Dispositivo de Áudio",
        "tts_device_label": "Escolha o dispositivo de saída:",
        "no_tts_device": "Nenhum dispositivo encontrado!",
        "menu_shortcuts": "ショートカット",
        "menu_configure_fish": "Configurar Fish Audio...",
        "fish_setup_title": "Configurar Fish Audio",
        "fish_key_placeholder": "Cole sua chave Fish Audio aqui...",
        "fish_voice_placeholder": "ID da voz (opcional)",
        "fish_configured": "Fish Audio configurado! ^_^",
        "fish_no_key": "Não colou nenhuma chave...",
        "menu_libras": "Traducao para Libras (escrita)",
    },
    "en": {
        "greeting": "Hii! So good to see you! ^_^",
        "ollama_started": "Ollama started! Ready to chat! ^_^",
        "ollama_not_found": "Hmm, couldn't find Ollama... I'll use preset phrases instead!",
        "history_cleared": "History cleared! ^_^",
        "no_mic_found": "No microphone found!",
        "mic_configured": "Microphone configured! ^_^",
        "gemini_configured": "Gemini configured! I'll use Google's AI! ^_^",
        "gemini_no_key": "No key provided... Try again!",
        "groq_configured": "Groq configured! I'll use the fastest AI! ^_^",
        "groq_no_key": "No key provided... Try again!",
        "hf_configured": "HuggingFace configured! Now I'll use the community's AI! ^_^",
        "hf_no_token": "No token provided... Try again!",
        "profile_saved_name": "Got it! I'll call you {name} now! ^_^",
        "profile_saved": "Profile updated! ^_^",
        "restarting_model": "Restarting to load {model}...",
        "alarm_stopped_generic": "Alarm time! 🎵",
        "alarm_stopped_msg": "Alarm turned off! ^_^",
        "alarm_deleted": "Alarm removed!",
        "alarm_added": "Alarm added! 💃",
        "speech_timer_title": "Speech Timer",
        "accessibility_interval_title": "Auto-reading interval",
        "accessibility_min_title": "Minimum between readings",
        "accessibility_max_title": "Maximum between readings",
        "audio_interval_title": "Audio transcription interval",
        "audio_min_title": "Minimum between audios",
        "audio_max_title": "Maximum between audios",
        "speech_min_title": "Minimum interval between speeches",
        "speech_max_title": "Maximum interval between speeches",
        "speech_exact_title": "Exact interval between speeches",
        "window_scale_title": "Window Size",
        "mic_device_title": "Microphone Device",
        "global_shortcut_title": "Global Shortcut (Win+V)",
        "stt_shortcut_title": "Microphone Shortcut",
        "gemini_setup_title": "Configure Gemini",
        "groq_setup_title": "Configure Groq",
        "hf_setup_title": "Configure HuggingFace",
        "profile_title": "My Profile",
        "add_alarm_title": "Add Alarm",
        "speech_timer_label": "After how many seconds should the pet speak?",
        "accessibility_interval_label": "Every how many seconds should the screen be read?",
        "accessibility_min_label": "Minimum seconds between readings?",
        "accessibility_max_label": "Maximum seconds between readings?",
        "audio_interval_label": "Every how many seconds should audio be transcribed?",
        "audio_min_label": "Minimum seconds between transcriptions?",
        "audio_max_label": "Maximum seconds between transcriptions?",
        "speech_min_label": "Minimum seconds between random speech?",
        "speech_max_label": "Maximum seconds between random speech?",
        "speech_exact_label": "Every how many seconds should the pet speak?",
        "window_scale_label": "Adjust the pet's window size:",
        "window_scale_default_mark": "Default",
        "mic_device_label": "Choose the input device:",
        "mic_choose_device": "Microphone Device",
        "btn_cancel": "Cancel",
        "btn_ok": "Ok",
        "btn_save": "Save",
        "btn_add": "Add",
        "global_shortcut_markup": "<b>Global Shortcut: Win + V</b>\n\nThe <b>Win+V</b> shortcut lets you press-to-talk from anywhere on the screen, even when the app is not focused.\n\nTo use it, add this line to your\ncompositor shortcuts file:\n\n<tt><span size=\"smaller\">Mod+V  {{ spawn-sh \"bash {path} toggle\"; }}</span></tt>\n\nOr run manually:\n<tt><span size=\"smaller\">bash {path} press   # start recording\nbash {path} release # stop recording\nbash {path} toggle  # toggle on/off</span></tt>",
        "stt_shortcut_markup": "<b>Press-to-Talk Shortcut</b>\n\nThis key works when the app is in focus.\nUse <b>Win+V</b> (global shortcut) for it to work\nfrom anywhere on the screen.\n\nPress the desired key in the field below.\nHold to record, release to transcribe.\n\nCurrent: <b>{current}</b>",
        "gemini_markup": "<b>Gemini API Key</b>\n\nGemini has a generous free plan (60 req/min).\n\n1. Visit: https://aistudio.google.com/apikey\n2. Click \"Create API Key\"\n3. Copy the key and paste it below\n\nNo credit card required.",
        "groq_markup": "<b>Groq API Key</b>\n\nGroq is 100% free and VERY fast!\nIt uses its own GPU (LPU) to run Llama 3, Gemma, and Mixtral.\n\n1. Visit: https://console.groq.com/keys\n2. Click \"Create API Key\"\n3. Copy the key and paste it below\n\nNo credit card needed. ~600 req/day free!",
        "hf_markup": "<b>HuggingFace API Token</b>\n\nHuggingFace offers free inference with a token!\nUse models like DialoGPT to chat.\n\n1. Visit: https://huggingface.co/settings/tokens\n2. Click \"New token\"\n3. Choose \"read\" permission and copy the token\n4. Paste it below\n\nFree, no credit card!",
        "profile_markup": "<b>How the AI should address you</b>\n\nThis data is saved locally and used\nonly for the AI to get to know you better.",
        "add_alarm_markup": "<b>New Alarm</b>\n\nPick a time. You can create as many as you want!",
        "add_alarm_name_placeholder": "Ex: Wake up, Lunch, Medicine...",
        "add_alarm_hour_label": "Hour:",
        "add_alarm_min_label": "Min:",
        "add_alarm_name_label": "Name (optional):",
        "menu_chat": "Chat",
        "menu_alarm": "Alarm",
        "menu_add_alarm": "Add alarm...",
        "menu_stop_alarm": "Stop Alarm",
        "menu_model": "Pet model",
        "menu_settings": "Settings",
        "menu_appearance": "🖥 Appearance",
        "menu_always_on_top": "Always on top",
        "menu_wallpaper": "Wallpaper mode",
        "menu_fullscreen": "Fullscreen",
        "menu_bubble_side": "Bubble side",
        "menu_bubble_auto": "Auto",
        "menu_bubble_left": "Left",
        "menu_bubble_right": "Right",
        "menu_window_size": "Window size...",
        "menu_automation": "🤖 Automation",
        "menu_model_defaults": "Model Defaults",
        "menu_screen_reading": "Screen reading",
        "menu_enable": "Enable",
        "menu_random": "Random",
        "menu_exact": "Exact",
        "menu_minimum": "Minimum...",
        "menu_maximum": "Maximum...",
        "menu_interval": "Interval...",
        "menu_desktop_audio": "Desktop audio",
        "menu_random_speech": "Random speech",
        "menu_timer": "Timer...",
        "menu_audio_cfg": "🎤 Audio",
        "menu_mic_stt": "Microphone (STT)",
        "menu_hold_to_talk": "Hold to talk",
        "menu_mic_open": "Open microphone",
        "menu_mic_shortcut": "Microphone shortcut...",
        "menu_global_shortcut": "Global shortcut (Win+V)...",
        "menu_mic_device": "Microphone device...",
        "menu_intelligence": "🧠 Intelligence",
        "menu_ai_provider": "AI Provider",
        "menu_provider_auto": "Automatic",
        "menu_provider_groq": "Groq (free)",
        "menu_provider_gemini": "Gemini (Google)",
        "menu_provider_hf": "API (Hugging Face)",
        "menu_provider_ollama": "Ollama (local)",
        "menu_provider_phrases": "Preset phrases",
        "menu_configure_gemini": "Configure Gemini...",
        "menu_configure_groq": "Configure Groq...",
        "menu_configure_hf": "Configure HuggingFace...",
        "menu_ollama_model": "Ollama Model",
        "menu_permissions": "Permissions",
        "menu_perm_read_file": "Read files",
        "menu_perm_list_files": "List folders",
        "menu_perm_run_command": "Run commands",
        "menu_perm_write_file": "Write files",
        "menu_perm_screenshot": "Take screenshot",
        "menu_perm_open_url": "Open URLs",
        "menu_perm_listen": "Listen to desktop sounds",
        "menu_profile": "👤 My Profile...",
        "menu_about": "ℹ About",
        "menu_clear_history": "Clear History",
        "menu_quit": "Quit",
        "menu_language": "🌐 Language",
        "about_comments": "A virtual pet by Kasane Teto",
        "profile_name_label": "Your name:",
        "profile_name_placeholder": "Ex: John, Jane...",
        "profile_bio_label": "Extra details (optional):",
        "profile_bio_placeholder": "Ex: pronouns, age, nickname...",
        "gemini_entry_placeholder": "Paste your Gemini key here...",
        "groq_entry_placeholder": "Paste your Groq key here...",
        "hf_entry_placeholder": "Paste your HuggingFace token here...",
        "gemini_link_label": "Open Google AI Studio",
        "groq_link_label": "Open Groq Console",
        "hf_link_label": "Open HuggingFace Tokens",
        "stt_shortcut_placeholder": "Press a key",
        "alarm_toggle_label": "Enabled",
        "alarm_delete_label": "Delete",
        "alarm_stopped": "Alarm turned off! ^_^",
        "alarm_deleted_msg": "Alarm removed!",
        "alarm_added_msg": "Alarm added! 💃",
        "menu_tts": "Assistant Voice",
        "menu_mic_mode": "Mic mode",
        "menu_tts_provider": "Voice Provider",
        "tts_provider_auto": "Automatic",
        "tts_provider_fish": "Fish Audio",
        "tts_provider_edge": "Edge-TTS",
        "tts_provider_pyttsx": "pyttsx3",
        "menu_tts_device": "Output device...",
        "tts_device_title": "Audio Device",
        "tts_device_label": "Choose output device:",
        "no_tts_device": "No device found!",
        "menu_shortcuts": "Shortcuts",
        "menu_configure_fish": "Configure Fish Audio...",
        "fish_setup_title": "Configure Fish Audio",
        "fish_key_placeholder": "Paste your Fish Audio key here...",
        "fish_voice_placeholder": "Voice ID (optional)",
        "fish_configured": "Fish Audio configured! ^_^",
        "fish_no_key": "No key pasted...",
        "menu_libras": "Translate to Libras (written)",
    },
    "jp": {
        "greeting": "やあ！会えて嬉しいよ！ ^_^",
        "ollama_started": "Ollama起動！おしゃべりできるよ！ ^_^",
        "ollama_not_found": "うーん、Ollamaが見つからない… 定型文を使うね！",
        "history_cleared": "履歴を消したよ！ ^_^",
        "no_mic_found": "マイクが見つかりません！",
        "mic_configured": "マイクを設定したよ！ ^_^",
        "gemini_configured": "Geminiを設定したよ！GoogleのAIを使うね！ ^_^",
        "gemini_no_key": "キーが貼られてないよ… もう一度試して！",
        "groq_configured": "Groqを設定したよ！最速のAIを使うね！ ^_^",
        "groq_no_key": "キーが貼られてないよ… もう一度試して！",
        "hf_configured": "HuggingFaceを設定したよ！コミュニティのAIを使うね！ ^_^",
        "hf_no_token": "トークンが貼られてないよ… もう一度試して！",
        "profile_saved_name": "わかった！これから{name}って呼ぶね！ ^_^",
        "profile_saved": "プロフィールを更新したよ！ ^_^",
        "restarting_model": "{model}を読み込むために再起動するね…",
        "alarm_stopped_generic": "アラームの時間だよ！ 🎵",
        "alarm_stopped_msg": "アラームを止めたよ！ ^_^",
        "alarm_deleted": "アラームを削除したよ！",
        "alarm_added": "アラームを追加したよ！ 💃",
        "speech_timer_title": "発話タイマー",
        "accessibility_interval_title": "自動読み上げ間隔",
        "accessibility_min_title": "読み上げ最小間隔",
        "accessibility_max_title": "読み上げ最大間隔",
        "audio_interval_title": "音声文字起こし間隔",
        "audio_min_title": "音声最小間隔",
        "audio_max_title": "音声最大間隔",
        "speech_min_title": "発話最小間隔",
        "speech_max_title": "発話最大間隔",
        "speech_exact_title": "発話の正確な間隔",
        "window_scale_title": "ウィンドウサイズ",
        "mic_device_title": "マイクデバイス",
        "global_shortcut_title": "グローバルショートカット (Win+V)",
        "stt_shortcut_title": "マイクショートカット",
        "gemini_setup_title": "Geminiの設定",
        "groq_setup_title": "Groqの設定",
        "hf_setup_title": "HuggingFaceの設定",
        "profile_title": "マイプロフィール",
        "add_alarm_title": "アラーム追加",
        "speech_timer_label": "何秒後にペットに話させますか？",
        "accessibility_interval_label": "何秒ごとに画面を読み上げますか？",
        "accessibility_min_label": "読み上げの最小秒数は？",
        "accessibility_max_label": "読み上げの最大秒数は？",
        "audio_interval_label": "何秒ごとに音声を文字起こししますか？",
        "audio_min_label": "文字起こしの最小秒数は？",
        "audio_max_label": "文字起こしの最大秒数は？",
        "speech_min_label": "ランダム発話の最小秒数は？",
        "speech_max_label": "ランダム発話の最大秒数は？",
        "speech_exact_label": "何秒ごとにペットに話させますか？",
        "window_scale_label": "ペットのウィンドウサイズを調整：",
        "window_scale_default_mark": "デフォルト",
        "mic_device_label": "入力デバイスを選んで：",
        "mic_choose_device": "マイクデバイス",
        "btn_cancel": "キャンセル",
        "btn_ok": "OK",
        "btn_save": "保存",
        "btn_add": "追加",
        "global_shortcut_markup": "<b>グローバルショートカット：Win + V</b>\n\n<b>Win+V</b>ショートカットを使うと、アプリにフォーカスがなくても画面のどこからでもプッシュトークが使えます。\n\n使うには、コンポジターのショートカットファイルに\n次の行を追加してください：\n\n<tt><span size=\"smaller\">Mod+V  {{ spawn-sh \"bash {path} toggle\"; }}</span></tt>\n\nまたは手動で実行：\n<tt><span size=\"smaller\">bash {path} press   # 録音開始\nbash {path} release # 録音停止\nbash {path} toggle  # オン/オフ切替</span></tt>",
        "stt_shortcut_markup": "<b>プッシュトークのショートカット</b>\n\nこのキーはアプリにフォーカスがあるときに機能します。\n画面のどこからでも使うには\n<b>Win+V</b>（グローバルショートカット）を使ってください。\n\n下のフィールドで希望のキーを押してください。\n押している間録音、離すと文字起こしします。\n\n現在：<b>{current}</b>",
        "gemini_markup": "<b>Gemini APIキー</b>\n\nGeminiには generous な無料プランがあります（60 req/min）。\n\n1. アクセス：https://aistudio.google.com/apikey\n2. 「Create API Key」をクリック\n3. キーをコピーして下に貼り付け\n\nクレジットカードは不要です。",
        "groq_markup": "<b>Groq APIキー</b>\n\nGroqは100％無料でとっても速い！\n独自GPU（LPU）を使ってLlama 3、Gemma、Mixtralを実行します。\n\n1. アクセス：https://console.groq.com/keys\n2. 「Create API Key」をクリック\n3. キーをコピーして下に貼り付け\n\nクレジットカード不要。約600 req/日無料！",
        "hf_markup": "<b>HuggingFace APIトークン</b>\n\nHuggingFaceはトークンで無料推論を提供！\nDialoGPTなどのモデルを使って会話できます。\n\n1. アクセス：https://huggingface.co/settings/tokens\n2. 「New token」をクリック\n3. 「read」権限を選んでトークンをコピー\n4. 下に貼り付け\n\n無料、クレジットカード不要！",
        "profile_markup": "<b>AIがあなたをどう呼ぶか</b>\n\nこのデータはローカルに保存され、\nAIがあなたをよりよく知るためだけに使われます。",
        "add_alarm_markup": "<b>新しいアラーム</b>\n\n時間を選んでね。いくつでも作れるよ！",
        "add_alarm_name_placeholder": "例：起床、昼食、薬…",
        "add_alarm_hour_label": "時：",
        "add_alarm_min_label": "分：",
        "add_alarm_name_label": "名前（任意）：",
        "menu_chat": "会話",
        "menu_alarm": "アラーム",
        "menu_add_alarm": "アラーム追加...",
        "menu_stop_alarm": "アラーム停止",
        "menu_model": "ペットのモデル",
        "menu_settings": "設定",
        "menu_appearance": "🖥 外観",
        "menu_always_on_top": "常に最前面",
        "menu_wallpaper": "壁紙モード",
        "menu_fullscreen": "フルスクリーン",
        "menu_bubble_side": "吹き出しの位置",
        "menu_bubble_auto": "自動",
        "menu_bubble_left": "左",
        "menu_bubble_right": "右",
        "menu_window_size": "ウィンドウサイズ...",
        "menu_automation": "🤖 自動化",
        "menu_model_defaults": "モデルのデフォルト",
        "menu_screen_reading": "画面読み上げ",
        "menu_enable": "有効",
        "menu_random": "ランダム",
        "menu_exact": "正確",
        "menu_minimum": "最小...",
        "menu_maximum": "最大...",
        "menu_interval": "間隔...",
        "menu_desktop_audio": "デスクトップ音声",
        "menu_random_speech": "ランダム発話",
        "menu_timer": "タイマー...",
        "menu_audio_cfg": "🎤 オーディオ",
        "menu_mic_stt": "マイク (STT)",
        "menu_hold_to_talk": "プッシュトーク",
        "menu_mic_open": "マイク開放",
        "menu_mic_shortcut": "マイクショートカット...",
        "menu_global_shortcut": "グローバルショートカット (Win+V)...",
        "menu_mic_device": "マイクデバイス...",
        "menu_intelligence": "🧠 インテリジェンス",
        "menu_ai_provider": "AIプロバイダー",
        "menu_provider_auto": "自動",
        "menu_provider_groq": "Groq（無料）",
        "menu_provider_gemini": "Gemini（Google）",
        "menu_provider_hf": "API（Hugging Face）",
        "menu_provider_ollama": "Ollama（ローカル）",
        "menu_provider_phrases": "定型文",
        "menu_configure_gemini": "Geminiを設定...",
        "menu_configure_groq": "Groqを設定...",
        "menu_configure_hf": "HuggingFaceを設定...",
        "menu_ollama_model": "Ollamaモデル",
        "menu_permissions": "権限",
        "menu_perm_read_file": "ファイル読み取り",
        "menu_perm_list_files": "フォルダ一覧表示",
        "menu_perm_run_command": "コマンド実行",
        "menu_perm_write_file": "ファイル書き込み",
        "menu_perm_screenshot": "スクリーンショット撮影",
        "menu_perm_open_url": "URLを開く",
        "menu_perm_listen": "デスクトップ音声を聴く",
        "menu_profile": "👤 マイプロフィール...",
        "menu_about": "ℹ について",
        "menu_clear_history": "履歴を消去",
        "menu_quit": "終了",
        "menu_language": "🌐 言語",
        "about_comments": "Kasane Tetoによるバーチャルペット",
        "profile_name_label": "あなたの名前：",
        "profile_name_placeholder": "例：太郎、花子...",
        "profile_bio_label": "追加情報（任意）：",
        "profile_bio_placeholder": "例：代名詞、年齢、ニックネーム...",
        "gemini_entry_placeholder": "Geminiキーをここに貼り付け...",
        "groq_entry_placeholder": "Groqキーをここに貼り付け...",
        "hf_entry_placeholder": "HuggingFaceトークンをここに貼り付け...",
        "gemini_link_label": "Google AI Studioを開く",
        "groq_link_label": "Groq Consoleを開く",
        "hf_link_label": "HuggingFace Tokensを開く",
        "stt_shortcut_placeholder": "キーを押してください",
        "alarm_toggle_label": "有効",
        "alarm_delete_label": "削除",
        "alarm_stopped": "アラームを止めたよ！ ^_^",
        "alarm_deleted_msg": "アラームを削除したよ！",
        "alarm_added_msg": "アラームを追加したよ！ 💃",
        "menu_tts": "アシスタント音声",
        "menu_mic_mode": "マイクモード",
        "menu_tts_provider": "音声プロバイダ",
        "tts_provider_auto": "自動",
        "tts_provider_fish": "Fish Audio",
        "tts_provider_edge": "Edge-TTS",
        "tts_provider_pyttsx": "pyttsx3",
        "menu_tts_device": "出力デバイス...",
        "tts_device_title": "オーディオデバイス",
        "tts_device_label": "出力デバイスを選択：",
        "no_tts_device": "デバイスが見つかりません！",
        "menu_shortcuts": "ショートカット",
        "menu_configure_fish": "Fish Audio設定...",
        "fish_setup_title": "Fish Audio設定",
        "fish_key_placeholder": "Fish Audioキーを貼り付け...",
        "fish_voice_placeholder": "音声ID（任意）",
        "fish_configured": "Fish Audio設定完了！^_^",
        "fish_no_key": "キーが貼り付けられていません...",
        "menu_libras": "Libras",
    },
}
